[[libsparseir]]
arch = "aarch64"
git-tree-sha1 = "383201ad7e730f06a7455d8aef57d3a0ea9a3735"
os = "macos"

    [[libsparseir.download]]
    sha256 = "e3f96d63b33d4791a555678fe3811c97cf4780d4d0ff6ac6537951a0ad904330"
    url = "https://github.com/shinaoka/libsparseir_jll.jl/releases/download/libsparseir-v0.7.2+0/libsparseir.v0.7.2.aarch64-apple-darwin.tar.gz"
